version: '3'
services:
  saw-script:
    build: ..
    entrypoint: ["cp", "/usr/local/bin/saw", "/saw-bin"]
    volumes:
      - ./bin:/saw-bin:rw

  s2n:
    build:
      context: .
      dockerfile: docker/s2n.dockerfile
    image: s2n
    volumes:
      - ./bin:/saw-bin:rw
